#!/usr/bin/env python

from flask import Flask, render_template, send_from_directory, Response
from glob import glob
import os
import sys
import time

app = Flask(__name__)

imgdir = sys.argv[1]
SUFFIXES = ['gif', 'jpg', 'png']


@app.route('/')
def index():
    images = sum([glob("%s/*.%s" % (imgdir, s)) for s in SUFFIXES], [])
    return render_template('base.html',
                           images=[os.path.basename(i) for i in images])


def event_stream():
    mtime = os.path.getmtime(imgdir)
    # TODO: eliminate polling
    while True:
        time.sleep(1)
        new_mtime = os.path.getmtime(imgdir)
        if new_mtime != mtime:
            mtime = new_mtime
            yield 'data: please reload\n\n'


@app.route('/stream')
def stream():
    return Response(event_stream(), mimetype="text/event-stream")


@app.route('/<path:path>')
def any(path):
    return send_from_directory(imgdir, path)


if __name__ == "__main__":
    app.debug = True
    app.run(threaded=True, port=8888)
